name: 🤖 Testing
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v2

      - name: Install Ruby
        with:
          bundler-cache: true

      - run: bundle exec rspec

